### ISSUE TITLE
Oracle-lookbusy通过dicker-compose运行后cpu占用一直增加

### ISSUE THREAD

**Issue by wxdjs** [Fog-Forest/scripts#2]
经过一晚上运行后lookbusy通过top查看cpu占用基本达到90%以上了

**Comment by Fog-Forest** [comment]
是新加坡X86机器吗

**Comment by wxdjs** [comment]
不是，是日本京东amd和韩国春川amd，我通过docker-compose down停止后在启动后就正常恢复设定值

**Comment by Fog-Forest** [comment]
已更新，增加了CPU核心限制，https://hub.docker.com/r/fogforest/lookbusy

**Comment by lion-goose** [comment]
> 是新加坡X86机器吗

新加坡AMD有什么问题吗，CPU很快就彪到100%，其他的地区AMD和ARM都正常，不知道问题在哪里
