### ISSUE TITLE
按最新脚本，cpu限制1，长时间运行cpu占用还是比较高

### ISSUE THREAD

**Issue by wxdjs** [Fog-Forest/scripts#3]
![image](https://user-images.githubusercontent.com/25563172/223297051-c57b8181-8a29-4ad9-8c35-5648557ef7d0.png)
![image](https://user-images.githubusercontent.com/25563172/223297144-3147f04c-bd47-4a4a-92dd-b298a60a9639.png)

**Comment by wxdjs** [comment]
因为已经停止docker了，我重新启动后
root@instance-20191022-0827:/home/ubuntu/oracle-lookbusy# ps -ef | grep lookbusy
root     20157 20068  0 01:50 ?        00:00:00 lookbusy -c 5-15 -r curve -m 45MB
root     20158 20157  0 01:50 ?        00:00:05 lookbusy -c 5-15 -r curve -m 45MB
root     20159 20157  0 01:50 ?        00:00:04 lookbusy -c 5-15 -r curve -m 45MB
root     20160 20157  3 01:50 ?        00:01:21 lookbusy -c 5-15 -r curve -m 45MB
root     21943 19798  0 02:31 pts/0    00:00:00 grep --color=auto lookbusy

**Comment by Fog-Forest** [comment]
看起来CPU核心数参数没有生效，可能是用的还是旧版容器镜像还是跑的全核心，请尝试重新拉取下新的容器镜像，然后再启动容器
```
docker compose pull
docker compose up -d
```
![image](https://user-images.githubusercontent.com/33511438/223305682-92774c55-586e-432a-b32b-fa28d6d51e6c.png)

**Comment by wxdjs** [comment]
ok, 感谢及时反馈，
